### ISSUE TITLE
YAS

### ISSUE THREAD

**Issue by darkdarcool** [JBYT27/BreakPC#1]
can't wait to break my computer :)

**Comment by JBYT27** [comment]
lmao yes xD

**Comment by darkdarcool** [comment]
ah yes. I also I found out hoot generate comments on Project Compliments

**Comment by IcingHackz** [comment]
>:( you broke my computer >:(

**Comment by darkdarcool** [comment]
Yas he did

**Comment by JBYT27** [comment]
lol
